### ISSUE TITLE
impl Renderable for Option<T> where T: Renderable

### ISSUE THREAD

**Issue by WIGGLES-dev** [vidhanio/hypertext#5]
This would allow easily mapping Options into lazy render functions with macros. The desired effect is that if a value is None, nothing is rendered.

This could also apply to other wrapper types like Arc, Rc, Box, Result, etc.

```
let user: Option<User> = get_user().await;

maud! {
  h1 { 
    ( user.map(|user| maud! { h1 { (user.name) } }) )
  }
}
```

Currently you have to do 
```
maud! {
  @if let Some(user) = user {

  }
}
```

Which isn't really awful, except it doesn't compose very well.

**Comment by vidhanio** [comment]
Done for `Option`, `Arc`, & `Rc`. update to `0.4.1` for new `impl`s.

`Box` unfortunately won't be possible as `Box<dyn FnOnce(&mut String)>` conflicts with the implementation on `FnOnce(&mut String)`.

I also would rather not do it for `Result` as `Result` probably makes more sense handled manually rather than automatically rendering the `Ok`/`Err` in the same place.

Thank you for the suggestion! :)
